import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/providers/clientProvider";
import { Kaushan_Script, Source_Sans_3 } from "next/font/google";

export const metadata: Metadata = {
  title: "Sachin Nimshan Official Website",
  description: "Generated by create next app",
};

const kaushan = Kaushan_Script({ subsets: ["latin"], weight: ["400"] });
const sourceSansPro = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceSansPro.className}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
